file(GLOB module_entries RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/*")
foreach(module_entry IN LISTS module_entries)
    if(IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${module_entry}")
        message(STATUS "Module: ${module_entry}")
        add_subdirectory("${module_entry}")
    endif()
endforeach()
